// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4sPA56TDJgb6vf4fs6gAM04zce_n_ojA',
    appId: '1:614642845835:web:8998fce3e0650b16836c8e',
    messagingSenderId: '614642845835',
    projectId: 'smart-edu-34284',
    authDomain: 'smart-edu-34284.firebaseapp.com',
    storageBucket: 'smart-edu-34284.firebasestorage.app',
    measurementId: 'G-Y20J9CJQ4N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2Yn56WxQ8WoEcEf8yZIUiT3gypNHTeNI',
    appId: '1:614642845835:android:9ac6acfefe9a2f62836c8e',
    messagingSenderId: '614642845835',
    projectId: 'smart-edu-34284',
    storageBucket: 'smart-edu-34284.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADcFFW0-jCmcaSo_f0Bu7THqy96qavei8',
    appId: '1:614642845835:ios:b21a80932aaa1171836c8e',
    messagingSenderId: '614642845835',
    projectId: 'smart-edu-34284',
    storageBucket: 'smart-edu-34284.firebasestorage.app',
    iosBundleId: 'com.example.smartEdu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADcFFW0-jCmcaSo_f0Bu7THqy96qavei8',
    appId: '1:614642845835:ios:b21a80932aaa1171836c8e',
    messagingSenderId: '614642845835',
    projectId: 'smart-edu-34284',
    storageBucket: 'smart-edu-34284.firebasestorage.app',
    iosBundleId: 'com.example.smartEdu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4sPA56TDJgb6vf4fs6gAM04zce_n_ojA',
    appId: '1:614642845835:web:b81ccd912cc094f1836c8e',
    messagingSenderId: '614642845835',
    projectId: 'smart-edu-34284',
    authDomain: 'smart-edu-34284.firebaseapp.com',
    storageBucket: 'smart-edu-34284.firebasestorage.app',
    measurementId: 'G-8Q76S8WT7R',
  );
}
